Get Requests
TechStreetDev/DFScript pull request #35
Opened 2023-05-22 19:15 UTC by XenithMusic

yo i did get requests for y'all

2023-05-22 19:31 UTC, GeorgeRNG requested changes
Unchecked GET requests

2023-05-22 19:31 UTC, GeorgeRNG commented on src/main/java/io/github/techstreet/dfscript/script/action/ScriptActionType.java
> +
A malformed URL should create an error in something like `ChatUtil.error` or preferably `OverlayManager.getInstance().add`

2023-05-22 19:31 UTC, GeorgeRNG commented on src/main/java/io/github/techstreet/dfscript/script/action/ScriptActionType.java
> +        .description("Makes a get request to the internet.")
With the nature of web requests, would describing how it works (sends only GET, how it fails on response, how it waits) be useful to have in the description?

2023-05-22 19:31 UTC, GeorgeRNG commented on src/main/java/io/github/techstreet/dfscript/script/action/ScriptActionType.java
> +        .icon(Items.GRASS_BLOCK)
I think something like a comparator/repeater or command block might be more fitting for a network request, if you are not going to use a head. I understand grass block as an alternative to earth but it doesn't fit "globe"?

2023-05-22 19:31 UTC, GeorgeRNG commented on src/main/java/io/github/techstreet/dfscript/script/action/ScriptActionType.java
> +            conn.setRequestMethod("GET");
Adding a method option and optional body (cannot be used in get) option would make it more flexible.

2023-05-31 20:00 UTC, TechStreetDev commented
@XenithMusic please make the requested changes.

2023-06-17 15:11 UTC, merged